src/Entity/Show.php
<?php

namespace App\Entity;

use App\Repository\ShowRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping\JoinColumn;

/**
 * @ORM\Entity(repositoryClass=ShowRepository::class)
 * @ORM\Table(name="`show`")
 * @UniqueEntity("slug")
 */
class Show
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
	

    private $id;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster_url;

    /**
     * @ORM\ManyToOne(targetEntity=Locations::class, inversedBy="shows")
	 * @JoinColumn(onDelete="RESTRICT")
     */
    private $location;

    /**
     * @ORM\Column(type="boolean")
     */
    private $bookable;

    /**
     * @ORM\Column(type="decimal", precision=12, scale=2, nullable=true)
     */
    private $price;

    /**
     * @ORM\OneToMany(targetEntity=Representation::class, mappedBy="the_show", orphanRemoval=true)
     */
   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPosterUrl(): ?string
    {
        return $this->poster_url;
    }

    public function setPosterUrl(?string $poster_url): self
    {
        $this->poster_url = $poster_url;

        return $this;
    }

    public function getLocation(): ?Locations
    {
        return $this->location;
    }

    public function setLocation(?Locations $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getBookable(): ?bool
    {
        return $this->bookable;
    }

    public function setBookable(bool $bookable): self
    {
        $this->bookable = $bookable;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(?string $price): self
    {
        $this->price = $price;

        return $this;
    }
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Representation", mappedBy="the_show", orphanRemoval=true)
     */
    private $representations;

    /**
     * @ORM\ManyToMany(targetEntity=ArtistsTypes::class, inversedBy="shows")
     */
    private $artistTypes;

    public function __construct()
    {
        $this->representations = new ArrayCollection();
        $this->artistTypes = new ArrayCollection();
    }

    /**
     * @return Collection|Representation[]
     */
    public function getRepresentations(): Collection
    {
        return $this->representations;
    }

    public function addRepresentation(Representation $representation): self
    {
        if (!$this->representations->contains($representation)) {
            $this->representations[] = $representation;
            $representation->setTheShow($this);
        }

        return $this;
    }

    public function removeRepresentation(Representation $representation): self
    {
        if ($this->representations->removeElement($representation)) {
            // set the owning side to null (unless already changed)
            if ($representation->getTheShow() === $this) {
                $representation->setTheShow(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ArtistsTypes[]
     */
    public function getArtistTypes(): Collection
    {
        return $this->artistTypes;
    }

    public function addArtistType(ArtistsTypes $artistType): self
    {
        if (!$this->artistTypes->contains($artistType)) {
            $this->artistTypes[] = $artistType;
        }

        return $this;
    }

    public function removeArtistType(ArtistsTypes $artistType): self
    {
        $this->artistTypes->removeElement($artistType);

        return $this;
    }
}

src/Controller/ShowController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Show;
class ShowController extends AbstractController
{
    /**
     * @Route("/show", name="show")
     */
    public function index(): Response
    {
                $repository = $this->getDoctrine()->getRepository(Show::class);
        $shows = $repository->findAll();
        
        return $this->render('show/index.html.twig', [
            'shows' => $shows,
            'resource' => 'spectacles',
        ]);

    }
	    /**
     * @Route("/show/{id}", name="show_show")
     */
    public function show($id)
    {
        $repository = $this->getDoctrine()->getRepository(Show::class);
        $show = $repository->find($id);
//Récupérer les artistes du spectacle et les grouper par type
        $collaborateurs = [];
        
        foreach($show->getArtistTypes() as $at) {
            $collaborateurs[$at->getType()->getType()][] = $at->getArtist();
        }

        return $this->render('show/show.html.twig', [
            'show' => $show,
	        'collaborateurs' => $collaborateurs,
        ]);
    }

}

templates/show/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des spectacles{% endblock %}

{% block body %}
<h1>Liste des {{ resource }}</h1>

    <ul>
    {% for show in shows %}
        <li><a href="{{ path('show_show', { id: show.id }) }}">{{ show.title }}
            {% if show.bookable %}
            <span>{{ show.price }} €</span>
            {% endif %}
			{% if show.representations|length==1 %}
            - <span>1 représentation</span>
            {% elseif show.representations|length>1 %}
            - <span>{{ show.representations|length }} représentations</span>
            {% else %}
            - <em>aucune représentation</em></a>
            {% endif %}

        </li>
    {% endfor %}
    </ul>

{% endblock %}

templates/show/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche d'un spectacle{% endblock %}

{% block body %}
<nav><a href="{{ path('show') }}">Retour à l'index</a></nav>
    <article>
        <h1>{{ show.title }}</h1>

        {% if show.posterUrl %}
        <p><img src="{{ asset('images/' ~ show.posterUrl) }}" alt="{{ show.title }}" width="200"></p>
        {% else %}
        <canvas width="200" height="100" style="border:1px solid #000000;"></canvas>
        {% endif %}

        {% if show.location %}
        <p><strong>Lieu de création:</strong> {{ show.location.designation }}</p>
        {% endif %}
        
       <p><strong>Prix:</strong> {{ show.price }} €</p>

        {% if show.bookable %}
        <p><em>Réservable</em></p>
        {% else %}
        <p><em>Non réservable</em></p>
        {% endif %}
		        <h2>Liste des représentations</h2>
        {% if show.representations|length>=1 %}
        <ul>
            {% for representation in show.representations %}
                <li>{{ representation.schedule|date('d/m/Y G:i:s') }}</li>              
            {% endfor %}
        </ul>
        {% else %}
        <p>Aucune représentation</p>
        {% endif %}
		        <h2>Liste des artistes</h2>
                <p><strong>Auteur:</strong>
        {% for auteur in collaborateurs['auteur'] %}
            {{ auteur.firstname }} 
            {{ auteur.lastname }}{% if loop.index == loop.length-1 %} et 
            {% elseif not loop.last %}, {% endif %}
        {% endfor %}
        </p>
        <p><strong>Metteur en scène:</strong>
        {% for scenographe in collaborateurs['scénographe'] %}
            {{ scenographe.firstname }} 
            {{ scenographe.lastname }}{% if loop.index == loop.length-1 %} et 
            {% elseif not loop.last %}, {% endif %}
        {% endfor %}
        </p>
        <p><strong>Distribution:</strong>
        {% for comedien in collaborateurs['comédien'] %}
            {{ comedien.firstname }} 
            {{ comedien.lastname }}{% if loop.index == loop.length-1 %} et 
            {% elseif not loop.last %}, {% endif %}
        {% endfor %}
        </p>

      


{% endblock %}