src/Entity/Representation.php
<?php

namespace App\Entity;

use App\Repository\RepresentationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @ORM\Entity(repositoryClass=RepresentationRepository::class)
 * @ORM\Table(name="representations")
 */
class Representation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Show::class, inversedBy="representations")
     * @ORM\JoinColumn(nullable=false, name="show_id", referencedColumnName="id", onDelete="RESTRICT")
     */
    private $the_show;

    /**
     * @ORM\Column(type="datetime")
     */
    private $schedule;

    /**
     * @ORM\ManyToOne(targetEntity=Locations::class, inversedBy="representations")
	 * @ORM\JoinColumn(name="location_id", referencedColumnName="id", onDelete="RESTRICT")
     */
    private $the_location;

    /**
     * @ORM\OneToMany(targetEntity=RepresentationUser::class, mappedBy="representation")
     */
    private $reservation;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="presentation", orphanRemoval=true)
     */
    private $reservations;

    public function __construct()
    {
        $this->reservation = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTheShow(): ?show
    {
        return $this->the_show;
    }

    public function setTheShow(?show $the_show): self
    {
        $this->the_show = $the_show;

        return $this;
    }

    public function getSchedule(): ?\DateTimeInterface
    {
        return $this->schedule;
    }

    public function setSchedule(\DateTimeInterface $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getTheLocation(): ?Locations
    {
        return $this->the_location;
    }

    public function setTheLocation(?Locations $the_location): self
    {
        $this->the_location = $the_location;

        return $this;
    }

    /**
     * @return Collection|RepresentationUser[]
     */
    public function getReservation(): Collection
    {
        return $this->reservation;
    }

    public function addReservation(RepresentationUser $reservation): self
    {
        if (!$this->reservation->contains($reservation)) {
            $this->reservation[] = $reservation;
            $reservation->setRepresentation($this);
        }

        return $this;
    }

    public function removeReservation(RepresentationUser $reservation): self
    {
        if ($this->reservation->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getRepresentation() === $this) {
                $reservation->setRepresentation(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }
}

src/Controller/RepresentationController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Representation;
class RepresentationController extends AbstractController
{
    /**
     * @Route("/representations", name="representations")
     */
    public function index(): Response
    {
		$repository = $this->getDoctrine()->getRepository(Representation::class);
        $representations = $repository->findAll();

        return $this->render('representation/index.html.twig', [
            'representations' => $representations,
            'resource' => 'représentations',

        ]);
    }
	    /**
     * @Route("/representations/{id}", name="representation_show")
     */
    public function show($id)
    {
        $repository = $this->getDoctrine()->getRepository(Representation::class);
        $representation = $repository->find($id);

        return $this->render('representation/show.html.twig', [
            'representation' => $representation,
        ]);
    }

}

templates/representation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des représentations{% endblock %}

{% block body %}
    <h1>Liste des {{ resource }}</h1>

    <ul>
    {% for representation in representations %}
        <li><a href="{{ path('representation_show', { id: representation.id }) }}">{{ representation.theShow.title }}
            {% if representation.theLocation %}
            - <span>{{ representation.theLocation.designation }}</span>
            {% endif %}
            - <datetime>{{ representation.schedule|date('d-m-Y H:i') }}</datetime></a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/representation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche d'une représentation{% endblock %}

{% block body %}
<nav><a href="{{ path('representations') }}">Retour à l'index</a></nav>
    <article>
        <h1>Représentation du {{ representation.schedule|date('d/m/Y') }} à {{ representation.schedule|date('G:i') }}</h1>
        <p><strong>Spectacle:</strong> {{ representation.theShow.title }}</p>

        <p><strong>Lieu:</strong> 
        {% if representation.theLocation %}
        {{ representation.theLocation.designation }}
        {% elseif representation.theShow.location %}
        {{ representation.theShow.theLocation.designation }}
        {% else %}
        <em>à déterminer</em>
        {% endif %}
        </p>
{% endblock %}